name: 'Deploy to Private Repo'
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Clone-to-Target-Repo:
    runs-on: ubuntu-latest
    environment: 
      name: ci-cd-env
    steps:
    - uses: actions/checkout@v4
    - name: "Build app and deploy to vercel" 
      uses: aasmal97/RepoSync@v1.0.0
      with: 
        TARGET_REPO_URL: ${{secrets.STUDY_AI_REPO_URL}}
        TARGET_REPO_BRANCH: main
        TARGET_REPO_GITHUB_ACCESS_TOKEN: ${{ secrets.STUDY_AI_REPO_ACCESS_TOKEN }} 
        BOT_NAME: testing-bot
        BOT_EMAIL: arkyasmal@gmail.com